Задачи из урока 1 : + задача 2
js-tasks-ru/jsbasic-20240321_3godas pull request #2
Opened 2024-03-26 18:37 UTC by DzmitryRamashka

2024-03-26 22:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-03-26 22:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-03-27 12:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-03-27 19:20 UTC, SinimaWath requested changes

2024-03-27 19:20 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return isSpam
тут нет необходимости по временной переменной:
`return Boolean(str.match(/1xBet/gi) || str.match(/XXX/gi)) `

Boolean - нужен чтобы явно привести операции к boolean

2024-03-28 08:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-28 08:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-03-29 07:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-03-29 13:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-03-29 19:28 UTC, DzmitryRamashka commented on 1-module/4-task/index.js
> +  return isSpam
Исправлено

2024-03-30 10:47 UTC, SinimaWath requested changes

2024-03-30 10:47 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if ( typeof(salaries[property]) === 'number' && !isNaN(salaries[property]) && salaries[property] != Infinity && salaries[property] != -Infinity) {
nit: Можно условие заменить на `Number.isFinite()`

2024-03-30 10:47 UTC, SinimaWath approved these changes

2024-03-30 10:47 UTC, merged