PR
js-tasks-ru/jsbasic-20240321_3godas pull request #3
Opened 2024-03-30 21:39 UTC by DzmitryRamashka

2024-03-30 21:40 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-03-31 10:40 UTC, SinimaWath requested changes

2024-03-31 10:40 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Тут надо использовать метод: `map` у массива:

`return users.map(...)`

2024-03-31 18:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-31 18:59 UTC, DzmitryRamashka commented on 3-module/1-task/index.js
> +  return names;
Исправлено

2024-03-31 21:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-01 15:57 UTC, SinimaWath approved these changes
Все круто!

2024-04-01 15:57 UTC, merged